/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static com.sun.webkit.perf.WCFontPerfLogger.reset;
import controller.RegionsController;
import dao.RegionsDAO;
import entities.Regions;
import java.math.BigDecimal;
import javax.swing.JOptionPane;


/**
 *
 * @author Fitriany Chairunnisa
 */
public class ViewRegion extends javax.swing.JFrame {
    private String header[]={"Region ID","Region Name"};      
    public RegionsController reg;
    private boolean hasil;
   
    /**
     * Creates new form ViewRegion
     */
    public ViewRegion() {
        initComponents();
        reg = new RegionsController();
        reg.bindingAll(tblRegions, header);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegions = new javax.swing.JTable();
        pnlRegion = new javax.swing.JPanel();
        lblRegionID = new javax.swing.JLabel();
        lblRegionName = new javax.swing.JLabel();
        tfRegionID = new javax.swing.JTextField();
        tfRegionName = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        tfSearch = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        cmbSearch = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblRegions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblRegions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRegions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegionsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegions);

        pnlRegion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlRegion.setName(""); // NOI18N

        lblRegionID.setText("Region ID");

        lblRegionName.setText("Region Name");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegionLayout = new javax.swing.GroupLayout(pnlRegion);
        pnlRegion.setLayout(pnlRegionLayout);
        pnlRegionLayout.setHorizontalGroup(
            pnlRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegionID)
                    .addComponent(lblRegionName))
                .addGap(30, 30, 30)
                .addGroup(pnlRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfRegionID)
                    .addComponent(tfRegionName))
                .addGap(119, 119, 119)
                .addGroup(pnlRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus))
                .addContainerGap())
        );
        pnlRegionLayout.setVerticalGroup(
            pnlRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegionID)
                    .addComponent(tfRegionID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan))
                .addGap(20, 20, 20)
                .addGroup(pnlRegionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegionName)
                    .addComponent(tfRegionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        cmbSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Region ID", "Region Name" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                        .addComponent(pnlRegion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari)
                    .addComponent(cmbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(pnlRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pnlRegion.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
       
        boolean hasil=false;
        if(!tfRegionID.isEnabled()){
         hasil=reg.update((Long.valueOf(tfRegionID.getText())),
         tfRegionName.getText());
                
     }
        else{
        hasil=reg.update((Long.valueOf(tfRegionID.getText())),
         tfRegionName.getText());
        }
        tfRegionID.setEnabled(true);
        btnSimpan.setEnabled(true);
        String pesan = "Gagal Menyimpan Data";
        if (hasil) {
            pesan ="Berhasil Menyimpan Data";
        } 
        JOptionPane.showMessageDialog(this, pesan);
        reg.bindingAll(tblRegions, header);
        reset();
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblRegionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegionsMouseClicked
      tfRegionID.setText(tblRegions.getValueAt(tblRegions.getSelectedRow(), 0)+"");
        tfRegionName.setText(tblRegions.getValueAt(tblRegions.getSelectedRow(), 1)+"");
        tfRegionID.setEnabled(false);
        btnSimpan.setEnabled(true);
        btnHapus.setEnabled(true);
    }//GEN-LAST:event_tblRegionsMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int i= JOptionPane.showConfirmDialog(this, "Yakin Mau Dihapus?");
        System.out.println(i);
        if(i==0){
        String pesan = "Gagal Hapus";
        boolean hasil = reg.delete(tfRegionID.getText());
        if (hasil) pesan="Berhasil Hapus";
        JOptionPane.showMessageDialog(this, pesan); 
            reg.bindingAll(tblRegions, header);
            
        }
        reset();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
    String kolom ="";
       switch (cmbSearch.getSelectedIndex()){
           case 0:kolom="region_id";break;
           case 1:kolom="region_name";break;
       }
        
        reg.bindingSearch(tblRegions, header, kolom, tfSearch.getText());
        System.out.println(cmbSearch.getSelectedItem()+"");
    }//GEN-LAST:event_btnCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRegion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRegion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRegion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRegion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRegion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRegionID;
    private javax.swing.JLabel lblRegionName;
    private javax.swing.JPanel pnlRegion;
    private javax.swing.JTable tblRegions;
    private javax.swing.JTextField tfRegionID;
    private javax.swing.JTextField tfRegionName;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables

          public void reset(){
        tfRegionID.setText("");
        tfRegionName.setText("");
        tfSearch.setText("");
        btnSimpan.setEnabled(false);
        btnHapus.setEnabled(false); 
        tfRegionID.setEnabled(true);
    }

}
