/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.JobsController;
import dao.JobsDAO;
import entities.Jobs;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dbayu
 */
public class ViewJobs extends javax.swing.JFrame {
     private String header[] = {"Job ID", "Job Title", "Minimum Salary", "Maximum Salary"};
    public JobsController jgc;
    


    /**
     * Creates new form ViewJobs
     */
    public ViewJobs() {
        initComponents();
        
        jgc = new JobsController();
        jgc.bindingall(tbl_jobs, header);
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_jobs = new javax.swing.JTable();
        txt_search = new javax.swing.JTextField();
        cmb_kategori = new javax.swing.JComboBox<>();
        btn_search = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_jobid = new javax.swing.JTextField();
        txt_jobTitle = new javax.swing.JTextField();
        txt_mimSalary = new javax.swing.JTextField();
        txt_maxSalary = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_jobs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_jobs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_jobsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_jobs);

        cmb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Job Id", "Job Title", "Minimum Salary", "Maximum Salary" }));

        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        jLabel1.setText("Job ID :");

        jLabel2.setText("Job Title :");

        jLabel3.setText("Minimum Salary :");

        jLabel4.setText("Maximum Salary :");

        txt_jobid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jobidActionPerformed(evt);
            }
        });
        txt_jobid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_jobidKeyPressed(evt);
            }
        });

        txt_jobTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jobTitleActionPerformed(evt);
            }
        });

        txt_mimSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mimSalaryActionPerformed(evt);
            }
        });

        txt_maxSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maxSalaryActionPerformed(evt);
            }
        });

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_jobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_maxSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jobid, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mimSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(193, 193, 193)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_jobid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_jobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_save))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_mimSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_maxSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_search))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search))
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_jobidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jobidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jobidActionPerformed

    private void txt_jobTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jobTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jobTitleActionPerformed

    private void txt_mimSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mimSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mimSalaryActionPerformed

    private void txt_maxSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maxSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maxSalaryActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
         boolean hasil = false;
        if (!txt_jobid.isEnabled()) {
            hasil = jgc.update(
                    txt_jobid.getText(),
                    txt_jobTitle.getText(),
                    Integer.parseInt(txt_mimSalary.getText()),
                    Integer.parseInt(txt_maxSalary.getText()));
        } else {
            hasil = jgc.insert(
                    txt_jobid.getText(),
                    txt_jobTitle.getText(),
                    Integer.parseInt(txt_mimSalary.getText()),
                    Integer.parseInt(txt_maxSalary.getText()));
        }
        String pesan = "gagal menginputkan data";
        if (hasil) {
            pesan = "berhasil menginputkan data";
        }
        JOptionPane.showMessageDialog(this, pesan);
        reset();
        jgc.bindingall(tbl_jobs, header);
        
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(this, "Apakah Anda Yakin Ingin dihapus?");
        if (i == 0) {
            String pesan = "Gagal hapus";
            boolean hasil = jgc.delete(txt_jobid.getText());
            if (hasil) {
                pesan = "Hore Berhasil";
            }
            JOptionPane.showMessageDialog(this, pesan);
            jgc.bindingall(tbl_jobs, header);

        }
        reset();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void tbl_jobsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_jobsMouseClicked
        // TODO add your handling code here:
        txt_jobid.setText(tbl_jobs.getValueAt(tbl_jobs.getSelectedRow(), 0).toString());
        txt_jobTitle.setText(tbl_jobs.getValueAt(tbl_jobs.getSelectedRow(), 1).toString());
        txt_mimSalary.setText(tbl_jobs.getValueAt(tbl_jobs.getSelectedRow(), 2).toString());
        txt_maxSalary.setText(tbl_jobs.getValueAt(tbl_jobs.getSelectedRow(), 3).toString());
        txt_jobid.setEnabled(false);
        btn_save.setEnabled(true);
        btn_delete.setEnabled(true);
    }//GEN-LAST:event_tbl_jobsMouseClicked

    private void txt_jobidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jobidKeyPressed
        // TODO add your handling code here:
        btn_save.setEnabled(true);
        btn_delete.setEnabled(true);
    }//GEN-LAST:event_txt_jobidKeyPressed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        String kolom = "";
        switch (cmb_kategori.getSelectedIndex()) {
            case 0:
                kolom = "jobId";
                break;
            case 1:
                kolom = "jobTitle";
                break;
            case 2:
                kolom = "minSalary";
                break;
            case 3:
                kolom = "maxSalary";
                break;
            default:
                throw new AssertionError();
        }
        jgc.bindingsearch(tbl_jobs, header, kolom,
                txt_search.getText());
    }//GEN-LAST:event_btn_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewJobs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox<String> cmb_kategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_jobs;
    private javax.swing.JTextField txt_jobTitle;
    private javax.swing.JTextField txt_jobid;
    private javax.swing.JTextField txt_maxSalary;
    private javax.swing.JTextField txt_mimSalary;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables

 public void reset() {
        txt_jobid.setText("");
        txt_jobTitle.setText("");
        txt_mimSalary.setText("");
        txt_maxSalary.setText("");
        txt_jobid.setEnabled(true);
        btn_save.setEnabled(false);
        btn_delete.setEnabled(false);
    }
 
 public void bindingTabel() {

        String header[] = {"Job ID", "Job Title", "Minimum Salary", "Maximum Salary"};
        List<Object> datas = new JobsDAO().getAll();
        Object[][] data = new Object[datas.size()][3];
        Jobs jobs= null;
        for (int i = 0; i < datas.size(); i++) {
             jobs = (Jobs) datas.get(i);
            data[i][0] = jobs.getJobId();
            data[i][1] = jobs.getJobTitle();
            data[i][2] = jobs.getMinSalary();
            data[i][3] = jobs.getMaxSalary();
        }
        DefaultTableModel model = new DefaultTableModel(data, header);
        tbl_jobs.setModel(model);
    }
}
